name = "imiles"
main = "./dist/_worker.js"
compatibility_date = "2026-03-31"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "imiles.me"
custom_domain = true

[assets]
directory = "./dist"
binding = "ASSETS"

# ----------------------------------------------------
# Cloudflare D1 关系型数据库绑定 (对应控制台已绑定的 BLOG-DB)
# ----------------------------------------------------
[[d1_databases]]
binding = "DB"
database_name = "BLOG-DB"
database_id = "24e0cea3-52ed-4685-bf64-001bc0e01d5f"
migrations_dir = "drizzle/migrations"

# ----------------------------------------------------
# Cloudflare Workers KV 键值缓存绑定 (对应控制台已绑定的 BOLG-KV)
# ----------------------------------------------------
[[kv_namespaces]]
binding = "KV"
id = "1bea21d899054b9eb223cb261f9b36c2"
