import { addCollection, Icon } from '@iconify/react';
import {
  ArrowRight,
  Check,
  CheckCircle2,
  Copy,
  ExternalLink,
  Loader2,
  RefreshCw,
  Server,
  Shield,
} from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/registry/shadcn/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/registry/shadcn/card';
import techIcons from '../../data/tech-icons.json';
import { adminApiRequest } from '../../lib/admin/api-client';
import { cn } from '../../lib/utils';
import type { AdminInfraConfig } from '../../shared/admin/infra-contract';
import type { AdminSession } from '../../shared/admin/session-contract';
import { AdminHeader } from './AdminHeader';
import { useAdminRouter } from './AdminRouterContext';
import { AdminSidebar } from './AdminSidebar';
import { AutoGeneratedAdminPage } from './AutoGeneratedAdminPage';
import { findNavItemByKey } from './config';
import { FriendLinkDetailPage } from './friend-links/FriendLinkDetailPage';
import { FriendLinksAdmin } from './friend-links/FriendLinksAdmin';

// 注册本地离线 Iconify 图标集合
addCollection(techIcons);

// ---------------------------------------------------------------------------
// 常量
// ---------------------------------------------------------------------------

/** 权限徽章样式与描述 */
const CAPABILITY_INFO: Record<string, { label: string; desc: string; color: string }> = {
  'admin:read': {
    label: '读取授权 (Read)',
    desc: '允许读取后台数据、审核申请流与系统配置',
    color: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-800 dark:text-emerald-300',
  },
  'admin:write': {
    label: '变更审核 (Write)',
    desc: '允许执行状态变更、审核发布、驳回与隐藏',
    color: 'border-blue-500/30 bg-blue-500/10 text-blue-800 dark:text-blue-300',
  },
  'admin:maintenance': {
    label: '维护清理 (Maintenance)',
    desc: '允许触发孤立对象清理、缓存刷新与批处理',
    color: 'border-purple-500/30 bg-purple-500/10 text-purple-800 dark:text-purple-300',
  },
};

// ---------------------------------------------------------------------------
// 链接构造工具
// ---------------------------------------------------------------------------

/** 构造 Cloudflare Dashboard 各资源的跳转 URL。accountId 缺失时返回 null。 */
function cfLinks(infra: AdminInfraConfig) {
  const acct = infra.cloudflare.accountId;
  if (!acct) return null;
  const base = `https://dash.cloudflare.com/${acct}`;
  const { workerName, d1DatabaseId, kvNamespaceId, sessionKvNamespaceId, accessApplicationId } =
    infra.cloudflare;
  return {
    dashboard: base,
    worker: workerName
      ? `${base}/workers/services/view/${workerName}/production`
      : `${base}/workers`,
    d1: d1DatabaseId ? `${base}/workers/d1/databases/${d1DatabaseId}/tables` : `${base}/workers/d1`,
    kv: kvNamespaceId
      ? `${base}/workers/kv/namespaces/${kvNamespaceId}`
      : `${base}/workers/kv/namespaces`,
    sessionKv: sessionKvNamespaceId
      ? `${base}/workers/kv/namespaces/${sessionKvNamespaceId}`
      : `${base}/workers/kv/namespaces`,
    access: accessApplicationId
      ? `${base}/zero-trust/access/apps/${accessApplicationId}`
      : `${base}/zero-trust/access/apps`,
    turnstile: `${base}/turnstile`,
  };
}

/** 构造 Supabase Dashboard 各资源的跳转 URL。 */
function sbLinks(infra: AdminInfraConfig) {
  const ref = infra.supabase.projectRef;
  if (!ref) return null;
  const base = `https://supabase.com/dashboard/project/${ref}`;
  return {
    project: base,
    storage: `${base}/storage/buckets`,
    settings: `${base}/settings/general`,
  };
}

// ---------------------------------------------------------------------------
// 子组件
// ---------------------------------------------------------------------------

/** 复制按钮图标（带反馈态） */
function CopyBtn({
  text,
  id,
  copiedKey,
  onCopy,
}: {
  text: string;
  id: string;
  copiedKey: string | null;
  onCopy: (text: string, key: string) => void;
}) {
  return (
    <button
      type="button"
      onClick={() => onCopy(text, id)}
      title="复制"
      className="shrink-0 text-muted-foreground hover:text-foreground transition-colors"
    >
      {copiedKey === id ? (
        <Check className="size-3 text-emerald-500" />
      ) : (
        <Copy className="size-3" />
      )}
    </button>
  );
}

/** 外链跳转按钮 */
function LinkBtn({ href, label }: { href: string; label: string }) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      title={label}
      className="inline-flex items-center gap-0.5 text-[10px] font-medium text-primary hover:underline underline-offset-2 shrink-0"
    >
      {label}
      <ExternalLink className="size-2.5" />
    </a>
  );
}

/** 规格行：标签 + 值 + 可选复制 + 可选跳转 */
function SpecRow({
  label,
  value,
  mono = true,
  copyId,
  copyText,
  href,
  hrefLabel,
  copiedKey,
  onCopy,
}: {
  label: string;
  value: string;
  mono?: boolean;
  copyId?: string;
  copyText?: string;
  href?: string | null;
  hrefLabel?: string;
  copiedKey: string | null;
  onCopy: (text: string, key: string) => void;
}) {
  return (
    <div className="flex items-center justify-between gap-2 py-0.5">
      <span className="shrink-0 text-muted-foreground">{label}</span>
      <div className="flex min-w-0 items-center gap-1.5">
        <span
          className={cn(
            'truncate text-foreground',
            mono ? 'font-mono text-[11px] font-medium' : 'text-xs',
          )}
          title={value}
        >
          {value}
        </span>
        {copyId && copyText && (
          <CopyBtn text={copyText} id={copyId} copiedKey={copiedKey} onCopy={onCopy} />
        )}
        {href && <LinkBtn href={href} label={hrefLabel ?? '打开'} />}
      </div>
    </div>
  );
}

/** 状态圆点 */
function Dot({ color = 'emerald' }: { color?: 'emerald' | 'amber' | 'slate' }) {
  const cls =
    color === 'emerald' ? 'bg-emerald-500' : color === 'amber' ? 'bg-amber-400' : 'bg-slate-400';
  return <span className={cn('size-1.5 rounded-full', cls)} />;
}

// ---------------------------------------------------------------------------
// DashboardView
// ---------------------------------------------------------------------------

function DashboardView({ session }: { session: AdminSession }) {
  const { navigate } = useAdminRouter();

  // 边缘延迟测速
  const [latency, setLatency] = useState<number | null>(null);
  const [probing, setProbing] = useState(false);

  // 基础设施配置（从 /api/v1/admin/infra 获取）
  const [infra, setInfra] = useState<AdminInfraConfig | null>(null);
  const [infraLoading, setInfraLoading] = useState(true);

  // 复制状态
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // ---------- 数据获取 ----------

  const probeLatency = useCallback(async () => {
    setProbing(true);
    const t0 = performance.now();
    try {
      await fetch('/api/v1/admin/session', { cache: 'no-store' });
      setLatency(Math.round(performance.now() - t0));
    } catch {
      setLatency(null);
    } finally {
      setProbing(false);
    }
  }, []);

  useEffect(() => {
    void probeLatency();
    const ctrl = new AbortController();
    adminApiRequest<AdminInfraConfig>('/api/v1/admin/infra', ctrl.signal)
      .then((data) => setInfra(data))
      .catch(() => setInfra(null))
      .finally(() => setInfraLoading(false));
    return () => ctrl.abort();
  }, [probeLatency]);

  // ---------- 辅助 ----------

  const copyText = useCallback((text: string, key: string) => {
    if (typeof navigator !== 'undefined') {
      void navigator.clipboard.writeText(text);
      setCopiedKey(key);
      setTimeout(() => setCopiedKey(null), 1500);
    }
  }, []);

  // 构造跳转链接（infra 加载完才有）
  const cf = infra ? cfLinks(infra) : null;
  const sb = infra ? sbLinks(infra) : null;

  // ---------- 服务卡片定义（依赖 infra） ----------

  type SpecItem = {
    label: string;
    value: string;
    mono?: boolean;
    copyId?: string;
    copyText?: string;
    href?: string | null;
    hrefLabel?: string;
  };

  type ServiceCard = {
    id: string;
    name: string;
    type: string;
    iconSlug: string;
    brandColor: string;
    description: string;
    status: string;
    statusColor?: 'emerald' | 'amber' | 'slate';
    dashLink: string | null;
    dashLabel: string;
    specs: SpecItem[];
  };

  const services: ServiceCard[] = infra
    ? [
        // 1. Cloudflare Access
        {
          id: 'cf-access',
          name: 'Cloudflare Access',
          type: 'Zero Trust 身份鉴权',
          iconSlug: 'cloudflare',
          brandColor: '#f38020',
          description:
            '管理后台基于 Cloudflare Zero Trust 实施边缘身份准入。每次请求强校验 JWT RS256 签名与 Issuer / Audience 白名单，失败立即关闭（Fail-closed）。',
          status: '已授权访问',
          dashLink: cf?.access ?? null,
          dashLabel: '打开 Access 控制台',
          specs: [
            {
              label: '认证身份',
              value: session.actor.kind === 'user' ? session.actor.email : session.actor.clientId,
              mono: false,
            },
            {
              label: '凭据类型',
              value:
                session.actor.kind === 'user'
                  ? '用户会话 (User JWT Assertion)'
                  : '服务密钥 (Service Token)',
              mono: false,
            },
            {
              label: '团队域名',
              value: infra.cloudflare.accessTeamName
                ? `${infra.cloudflare.accessTeamName}.cloudflareaccess.com`
                : '—',
              href: infra.cloudflare.accessTeamName
                ? `https://${infra.cloudflare.accessTeamName}.cloudflareaccess.com`
                : null,
              hrefLabel: '访问登录页',
            },
            {
              label: '应用 ID',
              value: infra.cloudflare.accessApplicationId ?? '—',
              copyId: 'cf-access-app-id',
              copyText: infra.cloudflare.accessApplicationId ?? '',
            },
          ],
        },

        // 2. Cloudflare D1
        {
          id: 'cf-d1',
          name: 'Cloudflare D1 数据库',
          type: 'Serverless SQLite',
          iconSlug: 'sqlite',
          brandColor: '#38bdf8',
          description:
            '全球分布式 Serverless SQL 数据库，使用 Drizzle ORM 强类型建模与版本化迁移管理，支持 D1 批量事务与幂等写入。',
          status: '已挂载',
          dashLink: cf?.d1 ?? null,
          dashLabel: '打开 D1 控制台',
          specs: [
            {
              label: '绑定名称',
              value: 'DB',
            },
            {
              label: '数据库名称',
              value: infra.cloudflare.d1DatabaseName ?? '—',
            },
            {
              label: '数据库 ID',
              value: infra.cloudflare.d1DatabaseId ?? '—',
              copyId: 'cf-d1-id',
              copyText: infra.cloudflare.d1DatabaseId ?? '',
              href: cf?.d1 ?? null,
              hrefLabel: '查看表结构',
            },
            {
              label: 'ORM 框架',
              value: 'Drizzle ORM · drizzle/migrations',
              mono: false,
            },
          ],
        },

        // 3. Cloudflare KV（业务缓存）
        {
          id: 'cf-kv',
          name: 'Cloudflare KV 缓存',
          type: '边缘分布式键值存储',
          iconSlug: 'cloudflare',
          brandColor: '#f38020',
          description:
            '毫秒级全球边缘分布式 KV 存储，承载公开友链聚合列表缓存（ETag + TTL）与 Astro 运行时会话状态，业务与会话双命名空间隔离。',
          status: '双 NS 就绪',
          dashLink: cf?.kv ?? null,
          dashLabel: '打开 KV 控制台',
          specs: [
            {
              label: '业务缓存 NS',
              value: infra.cloudflare.kvNamespaceName ?? 'KV',
              href: cf?.kv ?? null,
              hrefLabel: '查看',
            },
            {
              label: '业务缓存 ID',
              value: infra.cloudflare.kvNamespaceId ?? '—',
              copyId: 'cf-kv-id',
              copyText: infra.cloudflare.kvNamespaceId ?? '',
            },
            {
              label: '会话存储 NS',
              value: infra.cloudflare.sessionKvNamespaceName ?? 'SESSION',
              href: cf?.sessionKv ?? null,
              hrefLabel: '查看',
            },
            {
              label: '会话存储 ID',
              value: infra.cloudflare.sessionKvNamespaceId ?? '—',
              copyId: 'cf-session-kv-id',
              copyText: infra.cloudflare.sessionKvNamespaceId ?? '',
            },
          ],
        },

        // 4. Supabase S3 存储
        {
          id: 'supabase-s3',
          name: 'Supabase 对象存储',
          type: 'S3 兼容媒体存储',
          iconSlug: 'supabase',
          brandColor: '#3fcf8e',
          description:
            'Supabase S3 兼容高可用对象存储，托管全站媒体资源与自动抓取的友链站点高清截图。访问凭据严格保留在服务端，前端零泄露。',
          status: 'S3 已挂载',
          dashLink: sb?.storage ?? null,
          dashLabel: '打开 Storage 控制台',
          specs: [
            {
              label: '项目 Ref',
              value: infra.supabase.projectRef ?? '—',
              copyId: 'sb-ref',
              copyText: infra.supabase.projectRef ?? '',
              href: sb?.project ?? null,
              hrefLabel: '打开项目',
            },
            {
              label: '存储桶',
              value: infra.supabase.storageBucket ?? '—',
              href: sb?.storage ?? null,
              hrefLabel: '查看文件',
            },
            {
              label: '区域',
              value: infra.supabase.s3Region ?? '—',
              mono: false,
            },
            {
              label: '端点 Host',
              value: infra.supabase.s3EndpointHost ?? '—',
              mono: false,
            },
          ],
        },

        // 5. Cloudflare Workers 运行时
        {
          id: 'cf-workers',
          name: 'Cloudflare Workers',
          type: 'Serverless 边缘算力',
          iconSlug: 'cloudflare',
          brandColor: '#f38020',
          description:
            '基于 V8 Isolate 的轻量无服务器边缘计算，动静资源统一调度，全球 Anycast 超低延迟响应。nodejs_compat 已启用。',
          status: '运行中',
          dashLink: cf?.worker ?? null,
          dashLabel: '打开 Workers 控制台',
          specs: [
            {
              label: 'Worker 名称',
              value: infra.cloudflare.workerName ?? '—',
              href: cf?.worker ?? null,
              hrefLabel: '查看日志',
            },
            {
              label: 'Account ID',
              value: infra.cloudflare.accountId ?? '—',
              copyId: 'cf-account-id',
              copyText: infra.cloudflare.accountId ?? '',
              href: cf?.dashboard ?? null,
              hrefLabel: '控制台',
            },
            {
              label: '绑定域名',
              value: 'imiles.me',
              href: 'https://imiles.me',
              hrefLabel: '访问',
              mono: false,
            },
            {
              label: '兼容版本',
              value: '2026-03-31 · nodejs_compat',
              mono: false,
            },
          ],
        },

        // 6. Cloudflare Turnstile & 限流
        {
          id: 'cf-turnstile',
          name: 'Turnstile & 限流',
          type: '人机防护与流量治理',
          iconSlug: 'cloudflare',
          brandColor: '#f38020',
          description:
            '保护友链提交接口免受恶意爬虫与垃圾滥用，结合边缘级限流器保证服务稳定性。单 IP 60s 内最多 5 次，超限返回 HTTP 429。',
          status: '防御生效',
          dashLink: cf?.turnstile ?? null,
          dashLabel: '打开 Turnstile 控制台',
          specs: [
            {
              label: '挂件名称',
              value: infra.cloudflare.turnstileWidgetName ?? '—',
              href: cf?.turnstile ?? null,
              hrefLabel: '查看分析',
              mono: false,
            },
            {
              label: '限流绑定',
              value: 'FRIEND_LINK_RATE_LIMITER (ID: 1001)',
              mono: false,
            },
            {
              label: '限流配额',
              value: '5 req / 60s / IP',
              mono: false,
            },
            {
              label: '超限策略',
              value: 'HTTP 429 + Retry-After',
              mono: false,
            },
          ],
        },

        // 7. Resend 邮件通知
        {
          id: 'resend-email',
          name: 'Resend 邮件通知',
          type: '事务邮件网关',
          iconSlug: 'resend',
          brandColor: 'currentColor',
          description: infra.resend?.configured
            ? '基于 Resend HTTP API 的事务邮件服务，支持友链审批通知、管理员新申请提醒等自动化邮件。零 SDK 依赖，纯 Fetch 实现，适配 Edge Runtime。'
            : '邮件服务尚未配置 RESEND_API_KEY，审批通过通知与新申请提醒将自动跳过。请在 Cloudflare Secrets 中配置密钥以启用。',
          status: infra.resend?.configured ? '发信就绪' : '未配置',
          statusColor: infra.resend?.configured ? 'emerald' : 'amber',
          dashLink: 'https://resend.com/domains',
          dashLabel: '打开 Resend 控制台',
          specs: [
            {
              label: '服务状态',
              value: infra.resend?.configured ? 'API 密钥已配置' : 'RESEND_API_KEY 未设置',
              mono: false,
            },
            {
              label: '发件地址',
              value: infra.resend?.emailFrom ?? 'imiles <noreply@imiles.me>',
              mono: false,
            },
            {
              label: '已验证域名',
              value: infra.resend?.verifiedDomain ?? 'imiles.me',
              mono: false,
            },
            {
              label: '通知类型',
              value: '审批通知 · 新申请提醒',
              mono: false,
            },
          ],
        },
      ]
    : [];

  // ---------- 概览卡片数据（始终从 infra 派生，未加载时显示骨架） ----------

  const summaryCards = [
    {
      id: 'workers',
      label: '边缘计算',
      value: infra?.cloudflare.workerName ?? 'Workers',
      sub: 'Global Anycast',
      icon: <Icon icon="simple-icons:cloudflare" width={16} height={16} color="#f38020" />,
      link: cf?.worker,
    },
    {
      id: 'd1',
      label: '关系型数据库',
      value: infra?.cloudflare.d1DatabaseName ?? 'D1',
      sub: 'Drizzle ORM · SQLite',
      icon: <Icon icon="simple-icons:sqlite" width={16} height={16} color="#38bdf8" />,
      link: cf?.d1,
    },
    {
      id: 'kv',
      label: 'KV 键值缓存',
      value: infra?.cloudflare.kvNamespaceName ?? 'KV',
      sub: `SESSION: ${infra?.cloudflare.sessionKvNamespaceName ?? '—'}`,
      icon: <Icon icon="simple-icons:cloudflare" width={16} height={16} color="#f38020" />,
      link: cf?.kv,
    },
    {
      id: 'supabase',
      label: 'S3 对象存储',
      value: infra?.supabase.storageBucket ?? 'Supabase S3',
      sub: infra?.supabase.s3Region ?? '—',
      icon: <Icon icon="simple-icons:supabase" width={16} height={16} color="#3fcf8e" />,
      link: sb?.storage,
    },
    {
      id: 'email',
      label: '事务邮件',
      value: infra?.resend?.configured ? 'Resend' : '未配置',
      sub: infra?.resend?.emailFrom ?? 'noreply@imiles.me',
      icon: <Icon icon="simple-icons:resend" width={16} height={16} className="text-foreground" />,
      link: 'https://resend.com/domains',
      statusOk: infra?.resend?.configured ?? false,
    },
  ];

  // ---------- 渲染 ----------

  return (
    <div className="space-y-6">
      {/* ── 标题栏 ── */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="flex size-2 animate-pulse rounded-full bg-emerald-500" />
            <p className="text-sm font-medium text-primary">System Console</p>
          </div>
          <h1 className="mt-1.5 text-2xl font-semibold tracking-tight md:text-3xl">控制面板</h1>
          <p className="mt-1.5 max-w-2xl text-sm leading-6 text-muted-foreground">
            全站云原生基础设施运行状态、Cloudflare 边缘生态服务矩阵与业务管理总览。
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={probeLatency}
            disabled={probing}
            className="gap-1.5 text-xs"
          >
            <RefreshCw className={cn('size-3.5', probing && 'animate-spin')} />
            {probing ? '测速中…' : latency !== null ? `${latency} ms · 刷新` : '边缘测速'}
          </Button>

          <Button variant="outline" size="sm" asChild className="gap-1.5 text-xs">
            <a href="/" target="_blank" rel="noopener noreferrer">
              公开站点
              <ExternalLink className="size-3.5 text-muted-foreground" />
            </a>
          </Button>

          <Button
            size="sm"
            onClick={() => navigate('/admin/friend-links')}
            className="gap-1.5 text-xs"
          >
            友链管理
            <ArrowRight className="size-3.5" />
          </Button>
        </div>
      </div>

      {/* ── 四格概览卡片 ── */}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">
        {summaryCards.map((c) => (
          <Card key={c.id} className="shadow-xs">
            <CardHeader className="pb-2">
              <CardDescription className="flex items-center justify-between text-xs">
                {c.label}
                {c.icon}
              </CardDescription>
              <CardTitle className="truncate text-lg font-bold">{c.value}</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span className="truncate">{c.sub}</span>
                <span
                  className={cn(
                    'flex items-center gap-1 font-medium',
                    c.statusOk === false
                      ? 'text-amber-600 dark:text-amber-400'
                      : 'text-emerald-600 dark:text-emerald-400',
                  )}
                >
                  <Dot color={c.statusOk === false ? 'amber' : 'emerald'} />
                  {c.link ? (
                    <a
                      href={c.link}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:underline underline-offset-2"
                    >
                      {c.statusOk === false ? '待配置' : '就绪'}
                    </a>
                  ) : c.statusOk === false ? (
                    '待配置'
                  ) : (
                    '就绪'
                  )}
                </span>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* ── 云服务矩阵大卡片 ── */}
      <div>
        <div className="mb-3 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Server className="size-4 text-primary" />
            <h2 className="text-base font-semibold tracking-tight">全站云基础设施配置</h2>
          </div>
          <span className="text-xs text-muted-foreground">
            {infraLoading ? (
              <span className="flex items-center gap-1">
                <Loader2 className="size-3 animate-spin" />
                加载配置中…
              </span>
            ) : infra ? (
              `${infra.environment} · 真实配置已加载`
            ) : (
              '配置加载失败，部分数据不可用'
            )}
          </span>
        </div>

        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
          {infraLoading
            ? // 骨架屏：与真实卡片等数量
              Array.from({ length: 7 }).map((_, i) => (
                // biome-ignore lint/suspicious/noArrayIndexKey: static skeleton
                <Card key={i} className="animate-pulse shadow-xs">
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-2.5">
                      <div className="size-9 rounded-lg bg-muted" />
                      <div className="space-y-1.5">
                        <div className="h-3 w-32 rounded bg-muted" />
                        <div className="h-2.5 w-20 rounded bg-muted" />
                      </div>
                    </div>
                    <div className="mt-3 space-y-1.5">
                      <div className="h-2.5 w-full rounded bg-muted" />
                      <div className="h-2.5 w-4/5 rounded bg-muted" />
                    </div>
                  </CardHeader>
                  <CardContent className="pt-0">
                    <div className="space-y-2 rounded-md border bg-muted/20 p-2.5">
                      {Array.from({ length: 4 }).map((__, j) => (
                        // biome-ignore lint/suspicious/noArrayIndexKey: static skeleton
                        <div key={j} className="flex justify-between gap-2">
                          <div className="h-2.5 w-16 rounded bg-muted" />
                          <div className="h-2.5 w-24 rounded bg-muted" />
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))
            : services.map((svc) => (
                <Card key={svc.id} className="flex flex-col justify-between shadow-xs">
                  <CardHeader className="pb-3">
                    <div className="flex items-start justify-between gap-3">
                      {/* 图标 + 名称 */}
                      <div className="flex items-center gap-2.5">
                        <span className="flex size-9 shrink-0 items-center justify-center rounded-lg border bg-muted/30">
                          <Icon
                            icon={`simple-icons:${svc.iconSlug}`}
                            width={20}
                            height={20}
                            color={svc.brandColor}
                          />
                        </span>
                        <div>
                          <CardTitle className="text-sm font-semibold">{svc.name}</CardTitle>
                          <p className="text-[11px] text-muted-foreground">{svc.type}</p>
                        </div>
                      </div>

                      {/* 状态徽章 + 跳转链接 */}
                      <div className="flex flex-col items-end gap-1.5 shrink-0">
                        <span
                          className={cn(
                            'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium',
                            svc.statusColor === 'amber'
                              ? 'border-amber-500/30 bg-amber-500/10 text-amber-700 dark:text-amber-300'
                              : svc.statusColor === 'slate'
                                ? 'border-slate-500/30 bg-slate-500/10 text-slate-700 dark:text-slate-300'
                                : 'border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300',
                          )}
                        >
                          <Dot color={svc.statusColor ?? 'emerald'} />
                          {svc.status}
                        </span>
                        {svc.dashLink && (
                          <a
                            href={svc.dashLink}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-0.5 text-[10px] text-muted-foreground hover:text-primary transition-colors"
                          >
                            {svc.dashLabel}
                            <ExternalLink className="size-2.5" />
                          </a>
                        )}
                      </div>
                    </div>

                    <CardDescription className="mt-2 text-xs leading-5">
                      {svc.description}
                    </CardDescription>
                  </CardHeader>

                  <CardContent className="pt-0">
                    <div className="space-y-1 rounded-md border bg-muted/20 p-2.5 text-xs">
                      {svc.specs.map((spec) => (
                        <SpecRow
                          key={spec.label}
                          label={spec.label}
                          value={spec.value}
                          mono={spec.mono}
                          copyId={spec.copyId}
                          copyText={spec.copyText}
                          href={spec.href}
                          hrefLabel={spec.hrefLabel}
                          copiedKey={copiedKey}
                          onCopy={copyText}
                        />
                      ))}
                    </div>
                  </CardContent>
                </Card>
              ))}
        </div>
      </div>

      {/* ── 权限审计面板 ── */}
      <Card className="shadow-xs">
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <Shield className="size-4 text-primary" />
              <CardTitle className="text-base">管理员权限审计</CardTitle>
            </div>
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
              <span>
                身份：
                <span className="font-mono font-medium text-foreground">
                  {session.actor.kind === 'user' ? session.actor.email : session.actor.clientId}
                </span>
              </span>
              {infra && infra.adminEmails.length > 0 && (
                <span>
                  授权邮箱：
                  <span className="font-mono font-medium text-foreground">
                    {infra.adminEmails.join(' · ')}
                  </span>
                </span>
              )}
            </div>
          </div>
          <CardDescription>
            能力由 Cloudflare Access 会话服务端计算签名，客户端仅用于展示。每个 API
            端点均独立执行严格失败关闭鉴权。
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid gap-3 sm:grid-cols-3">
            {session.capabilities.map((cap) => {
              const info = CAPABILITY_INFO[cap] ?? {
                label: cap,
                desc: '系统基础运行权限',
                color: 'border-border bg-muted/40 text-foreground',
              };
              return (
                <div
                  key={cap}
                  className={cn(
                    'flex flex-col justify-between rounded-lg border p-3 text-xs transition-colors',
                    info.color,
                  )}
                >
                  <div className="flex items-center justify-between gap-2">
                    <span className="font-semibold">{info.label}</span>
                    <CheckCircle2 className="size-3.5 shrink-0 opacity-80" />
                  </div>
                  <p className="mt-2 text-[11px] leading-relaxed opacity-80">{info.desc}</p>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// ---------------------------------------------------------------------------
// AdminShell
// ---------------------------------------------------------------------------

/**
 * 后台管理应用外壳组件。
 * 负责整体左右分栏布局（左侧导航栏、顶部多标签栏与主视区路由视图分发）。
 * 自动支持 nav.ts 中配置的任意新功能模块（自动生成功能管理页）。
 */
export function AdminShell({
  session,
  section,
  friendLinkId,
}: {
  session: AdminSession;
  section: string;
  friendLinkId?: string;
}) {
  return (
    <div className="flex h-dvh min-h-[32rem] bg-muted/20">
      <AdminSidebar section={section} />
      <div className="flex min-w-0 flex-1 flex-col">
        <AdminHeader actor={session.actor} section={section} />
        <main id="admin-main" className="min-w-0 flex-1 overflow-y-auto p-4 md:p-6 lg:p-8">
          {section === 'friend-links' ? (
            friendLinkId ? (
              <FriendLinkDetailPage id={friendLinkId} session={session} />
            ) : (
              <FriendLinksAdmin session={session} />
            )
          ) : section === 'dashboard' ? (
            <DashboardView session={session} />
          ) : (
            <AutoGeneratedAdminPage navItem={findNavItemByKey(section)} session={session} />
          )}
        </main>
      </div>
    </div>
  );
}
