import {
  Activity,
  ArrowUpRight,
  Boxes,
  Code2,
  FolderGit2,
  Plus,
  RefreshCw,
  Search,
  Shield,
  SlidersHorizontal,
} from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/registry/shadcn/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/registry/shadcn/card';
import { cn } from '../../lib/utils';
import type { AdminSession } from '../../shared/admin/session-contract';
import type { AdminNavItem } from './config';

interface AutoGeneratedAdminPageProps {
  /** 当前模块导航配置项 */
  navItem?: AdminNavItem;
  /** 当前管理员会话 */
  session: AdminSession;
}

/**
 * 自动生成的通用后台功能管理页面。
 * 当在 nav.ts 中配置新导航项后，系统会自动为该路由生成开箱即用的功能管理页。
 * 包含：模块状态头、三栏指标卡片、快速操作工具栏、数据管理工作区以及开发者接入提示。
 */
export function AutoGeneratedAdminPage({ navItem, session }: AutoGeneratedAdminPageProps) {
  const [refreshing, setRefreshing] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');

  const title = navItem?.label ?? '功能模块';
  const description = navItem?.description ?? '此功能模块已通过 nav.ts 自动配置并生成管理界面。';
  const Icon = navItem?.icon ?? Boxes;
  const isEnabled = navItem?.enabled ?? true;

  const handleRefresh = () => {
    setRefreshing(true);
    setTimeout(() => setRefreshing(false), 600);
  };

  return (
    <div className="space-y-6">
      {/* 顶部标题与操作栏 */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <p className="text-sm font-medium text-primary">业务模块</p>
            <span className="text-muted-foreground/40">/</span>
            <span className="rounded bg-muted px-2 py-0.5 text-xs text-muted-foreground">
              {navItem?.key ?? 'module'}
            </span>
          </div>
          <h1 className="mt-1.5 flex items-center gap-2.5 text-2xl font-semibold tracking-tight md:text-3xl">
            <Icon className="size-7 text-primary" aria-hidden="true" />
            {title}
          </h1>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{description}</p>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={handleRefresh}
            disabled={refreshing}
            className="gap-1.5"
          >
            <RefreshCw className={cn('size-3.5', refreshing && 'animate-spin')} />
            刷新
          </Button>
          <Button size="sm" className="gap-1.5">
            <Plus className="size-3.5" />
            新建记录
          </Button>
        </div>
      </div>

      {/* 模块元数据与状态卡片 */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="shadow-xs">
          <CardHeader className="pb-2">
            <CardDescription className="flex items-center justify-between text-xs">
              运行状态
              <Activity className="size-3.5 text-muted-foreground" />
            </CardDescription>
            <CardTitle className="text-xl font-bold">
              {isEnabled ? (
                <span className="inline-flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400">
                  <span className="size-2 rounded-full bg-emerald-500" />
                  正常就绪
                </span>
              ) : (
                <span className="inline-flex items-center gap-1.5 text-amber-600 dark:text-amber-400">
                  <span className="size-2 rounded-full bg-amber-500" />
                  待接入
                </span>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">路由与客户端单页状态已连接</p>
          </CardContent>
        </Card>

        <Card className="shadow-xs">
          <CardHeader className="pb-2">
            <CardDescription className="flex items-center justify-between text-xs">
              配置路径
              <FolderGit2 className="size-3.5 text-muted-foreground" />
            </CardDescription>
            <CardTitle className="truncate font-mono text-base font-semibold">
              {navItem?.href ?? '/admin'}
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">已自动纳入客户端路由管理</p>
          </CardContent>
        </Card>

        <Card className="shadow-xs">
          <CardHeader className="pb-2">
            <CardDescription className="flex items-center justify-between text-xs">
              权限要求
              <Shield className="size-3.5 text-muted-foreground" />
            </CardDescription>
            <CardTitle className="text-base font-semibold">
              <code className="rounded bg-muted px-2 py-0.5 text-xs font-mono">
                {navItem?.requiredCapability ?? 'admin:read'}
              </code>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">
              当前用户拥有 {session.capabilities.length} 项授权
            </p>
          </CardContent>
        </Card>

        <Card className="shadow-xs">
          <CardHeader className="pb-2">
            <CardDescription className="flex items-center justify-between text-xs">
              页面模式
              <Code2 className="size-3.5 text-muted-foreground" />
            </CardDescription>
            <CardTitle className="text-base font-semibold">自动生成脚手架</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-xs text-muted-foreground">可在 nav.ts 维护专属业务视图</p>
          </CardContent>
        </Card>
      </div>

      {/* 模块工作区主卡片 */}
      <Card className="shadow-xs">
        <CardHeader>
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <CardTitle className="text-lg">数据与功能管理</CardTitle>
              <CardDescription className="mt-1">
                此页面已由后台统一导航机制自动挂载。您可以在此快速维护业务条目与触发操作。
              </CardDescription>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <div className="relative">
                <Search className="absolute left-2.5 top-2.5 size-3.5 text-muted-foreground" />
                <input
                  type="text"
                  placeholder="搜索数据..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="h-8 w-44 rounded-md border bg-background pl-8 pr-3 text-xs outline-none focus:ring-1 focus:ring-primary md:w-56"
                />
              </div>
              <Button variant="outline" size="sm" className="gap-1.5 text-xs">
                <SlidersHorizontal className="size-3" />
                筛选
              </Button>
            </div>
          </div>
        </CardHeader>
        <CardContent>
          <div className="rounded-lg border border-dashed p-8 text-center sm:p-12">
            <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary">
              <Icon className="size-6" />
            </div>
            <h3 className="mt-4 text-base font-semibold">{title}管理工作区就绪</h3>
            <p className="mx-auto mt-2 max-w-md text-xs leading-5 text-muted-foreground">
              当前页面已自动配置好 Header 标签页切换、侧栏联动与路由拦截。
              您可以随时在此接入真实的后端 API 接口与业务表格。
            </p>
            <div className="mt-6 flex flex-wrap justify-center gap-3">
              <Button size="sm" className="gap-1.5 text-xs">
                <Plus className="size-3.5" />
                创建首条数据
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="gap-1.5 text-xs"
                onClick={() => window.open('https://github.com/Max-Samson/imiles.me', '_blank')}
              >
                查看配置指南
                <ArrowUpRight className="size-3.5" />
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
