import type { D1Database, Fetcher, KVNamespace, RateLimit } from '@cloudflare/workers-types';
/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --env-interface WorkerBindings --include-runtime false` (hash: 991941012bf5ebe630e2c12dc369e67c)
interface __BaseEnv_WorkerBindings {
  KV: KVNamespace;
  SESSION: KVNamespace;
  DB: D1Database;
  FRIEND_LINK_RATE_LIMITER: RateLimit;
  ASSETS: Fetcher;
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}

export type { WorkerBindings };
