import type { D1Database, Fetcher, KVNamespace } from '@cloudflare/workers-types';
/* eslint-disable */
// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --env-interface WorkerBindings --include-runtime false` (hash: ba58029170d440e369a898a8990c053d)
interface __BaseEnv_WorkerBindings {
  KV: KVNamespace;
  DB: D1Database;
  ASSETS: Fetcher;
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}

export type { WorkerBindings };
